# Generated by Django 4.0.5 on 2022-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactNumber', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
