# Generated by Django 4.0.5 on 2022-07-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
