# Generated by Django 4.0.5 on 2022-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joiningDate',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
